# Generated by Django 4.0.3 on 2022-06-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Checkbox',
            new_name='CheckBox',
        ),
    ]
